### PR TITLE
snos for expiring NUH and IP ubans

### PR DESCRIPTION
**Pull request by mogad0n**
1. I haven't covered temporary account suspensions because I haven't found an easy way yet. I have some questions.
2. I had added `info.OperReason` but then if you don't provide a reason it just looks stupid at which point I was considering using the same process as done in `uban.go` with `announceUban()` which is to build a string. I feel like knowing why that ban was placed when it expires can be good for perspective.
3. I am not sure if the loglines as they are and Snos are acceptable wrt the language used and maybe some other things I haven't realized.
Given, the uncertainties mentioned above I chose to just create a PR to maybe get an idea from you folks if this is useful.

attempts to address #1613

### CODE REVIEW

**Comment by mogad0n** [comment]
`2021-07-18T20:57:09.015Z : info  : opers      : UBAN expiring for IP: [192.0.2.0] set on [Sun, 18 Jul 2021 20:56:39 UTC] added by: admin`
`2021-07-18T20:51:18.474Z : info  : opers      : UBAN expiring for NUH-mask: [wee!*@*] set on [Sun, 18 Jul 2021 20:50:48 UTC] added by: admin`

Are what the `server.logger.Info()` lines look like

**Comment by slingamn** [comment]
`defer`s execute in LIFO order, so they should be on the opposite side of the `Lock()` and `Unlock()` calls. Actually it's probably just fine to send them before the `Lock()` call, without using `defer`.

**Comment by mogad0n** [comment]
[RAW lines and logs](https://lsd25.dev/fG2MT) privatebin paste.

I did decide to send the snos and loglines before the `.Lock()` and use a function to build the strings.

I'm violating DRY with 2 of these `announces`, possibly.
As I mentioned in the channel It would be preferable to define this sort of an `announceExpire()` in a single place, This can be a utility even for chanbans and mutes which are timed.  #1513  

1) Are the changes and the codebase on the ride path?
2) The one stop shop function is it important or do I keep em all separate.

**Comment by mogad0n** [comment]
I think a clean, concise (DRY) implementation of this would require more work. I am retracting this PR for the time being. Hope that's not a problem.

**Pull request closed without merging**
