### PR TITLE
add FAIL AUTHENTICATE VERIFICATION_REQUIRED

### PR DESCRIPTION
**Pull request by slingamn**
From discussion with @emersion, this will help with UX if people try to
log into their unverified accounts.

### CODE REVIEW

**Comment by slingamn** [comment]
Example transcript:

```
authenticate plain
AUTHENTICATE +
authenticate YXNkZgBhc2RmAHNoaXZhcmFtcGFzc3BocmFzZQ==
:oragono.test 904 * :SASL authentication failed: Account is not yet verified
:oragono.test FAIL AUTHENTICATE VERIFICATION_REQUIRED * :Account is not yet verified
```

I left a `*` in there as a placeholder for a parameter that indicates the account name if it's known, mostly for parity with similar FAIL codes.

**Comment by emersion** [comment]
I don't really like using a `FAIL` for this. I'd prefer to use something like `NOTE`.

**Comment by slingamn** [comment]
How come? This seems to fall squarely within the definition of `FAIL` in the specification:

>The FAIL message indicates a complete failure to process a given command/function, or simply some error about the current session that clients should be aware of.

**Comment by emersion** [comment]
I'd like to re-use the same code in a server which doesn't fail auth for unverified accounts.

**Comment by slingamn** [comment]
Legit, I'll make it a `NOTE` then.

**Pull request merged**
